// Local screening: exact stems plus conservative lexical/paraphrase similarity.
// No question-paper content is sent to an external service.
const stop=new Set('a an the which what who how is are was were be been being of to in on for with by from and or as at that this these those following primarily main most best does do can would should used'.split(' '));
const synonyms={purpose:'objective',aim:'objective',aims:'objective',goal:'objective',goals:'objective',objectives:'objective',reason:'objective',identify:'determine',identifies:'determine',identifying:'determine',ascertain:'determine',establish:'determine',assess:'evaluate',assessment:'evaluate',evaluating:'evaluate',evaluation:'evaluate',measure:'evaluate',method:'technique',methods:'technique',techniques:'technique',approach:'technique',approaches:'technique',utilize:'use',utilise:'use',employ:'use',employed:'use',select:'choose',selection:'choose',choosing:'choose',increase:'raise',increases:'raise',decrease:'reduce',decreases:'reduce',reduction:'reduce',reliability:'consistent',consistency:'consistent',reliable:'consistent',accurate:'accuracy',precision:'accuracy',study:'research',investigation:'research',investigate:'research',randomized:'random',randomised:'random',chance:'random',participants:'participant',respondents:'participant',subjects:'participant',information:'data',observations:'data',relationship:'association',connection:'association',links:'association',variables:'variable',factors:'variable',difference:'variation',differences:'variation'};
function stem(text){return String(text).split(/(?:\(?A\)|\bA[.)])\s*/i)[0].replace(/^\s*(?:question\s*)?\d+[.)]?\s*/i,'').trim();}
function normal(text){return stem(text).normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();}
function tokens(text){return new Set(normal(text).split(/\s+/).filter(t=>t&&!stop.has(t)).map(t=>synonyms[t]||t.replace(/(ing|ed|s)$/,'')).filter(Boolean));}
function similarity(a,b){const x=normal(a),y=normal(b);if(x===y&&x)return {score:1,type:'Exact question'};const ta=tokens(a),tb=tokens(b);if(ta.size<3||tb.size<3)return {score:0};const negate=t=>/\b(not|except|never|incorrect|false|least)\b/.test(t);if(negate(x)!==negate(y))return {score:0};const numbers=t=>(t.match(/\b\d+\b/g)||[]).sort().join(',');if(numbers(x)!==numbers(y))return {score:0};const common=[...ta].filter(t=>tb.has(t)).length;const score=2*common/(ta.size+tb.size);return {score,type:'Possible rephrasing'};}
function screen(questions,archives,set){const matches=[];questions.forEach((q,i)=>{const hits=[];for(const archive of archives)archive.questions.forEach((old,j)=>{const result=similarity(q.text,old.text);if(result.score>=0.8)hits.push({upcoming_set:set,upcoming_question:i+1,upcoming_text:q.text,past_session:archive.session,past_set:archive.set_name,past_campus:archive.campus,past_question:j+1,past_text:old.text,past_file:archive.original_name,type:result.type,similarity:Math.round(result.score*100)});});if(hits.length)matches.push(...hits.sort((a,b)=>b.similarity-a.similarity));});const matchedCount=new Set(matches.map(m=>m.upcoming_question)).size;return {total_questions:questions.length,matched_count:matchedCount,limit:10,rejected:matchedCount>10,matches,method:'Local exact-question and likely-rephrasing screening; human review is still required.'};}
function departmentKey(d){if(d.name?.trim().toLowerCase()==="mathematics")return "mathematics|all faculties";if(d.is_common)return "common-research-methodology|"+d.faculty_code;const name=d.name.toLowerCase().replace(/\s*\(.*?\)/g,'').trim();const faculty=/engineering/i.test(d.institution)?'engineering':/management/i.test(d.institution)?'management':/dental/i.test(d.institution)?'dental':/allied|occupational/i.test(d.institution)?'health':'science';return name+'|'+faculty;}
module.exports={screen,similarity,departmentKey};
