const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),Zip=require('pizzip');
const {inspect,choose,generate}=require('./papers');
function fixture(prefix){const z=new Zip();const p=t=>`<w:p><w:r><w:t>${t}</w:t></w:r></w:p>`;let body='';for(const section of ['Research Methodology','Subject-Specific Questions']){body+=p(section);for(let i=0;i<25;i++)body+=p(`${i+1}. ${prefix} ${section} ${i}? A) alpha B) beta C) gamma D) delta`);}body+=p('Answer Key')+p('1 A');z.file('word/document.xml',`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}</w:body></w:document>`);return z.generate({type:'nodebuffer'});}
const pools=[1,2].map(campus=>({campus,path:'',questions:inspect(fixture('Campus'+campus)).questions}));
test('supplied template automatic option lists are extracted',()=>{const file=path.join(__dirname,'..','Question_Paper_Setting','Rmp_Department name_Jan_2027_QP_Set_A.docx');if(fs.existsSync(file)){const r=inspect(fs.readFileSync(file));assert.deepEqual(r.counts,{research:4,subject:4});assert.ok(r.questions[0].text.includes('A) Option A'));}});
test('extract exactly 25 + 25 and stop before key',()=>{const r=inspect(fixture('test'));assert.equal(r.valid,true);assert.deepEqual(r.counts,{research:25,subject:25});assert.equal(r.questions.length,50);});
test('question numbers determine count even with missing or reordered option labels',()=>{const z=new Zip(fixture('numbered'));z.file('word/document.xml',z.file('word/document.xml').asText().replaceAll('A) alpha B) beta C) gamma D) delta','D) delta A) alpha A) beta C) gamma'));const r=inspect(z.generate({type:'nodebuffer'}));assert.equal(r.questions.length,50);assert.deepEqual(r.counts,{research:25,subject:25});assert.equal(r.questions[0].number,1);assert.ok(r.questions[0].text.includes('D) delta'));});
test('missing section headings are reported rather than inferred from question numbers',()=>{const z=new Zip(fixture('numbered'));z.file('word/document.xml',z.file('word/document.xml').asText().replace(/<w:p><w:r><w:t>(Research Methodology|Subject-Specific Questions)<\/w:t><\/w:r><\/w:p>/g,''));const r=inspect(z.generate({type:'nodebuffer'}));assert.equal(r.counts.unclassified,50);assert.equal(r.valid,false);});
test('equal campus contribution and section totals',()=>{const qs=choose(pools);assert.equal(qs.length,50);assert.equal(qs.filter(q=>q.source.campus===1).length,25);assert.equal(qs.filter(q=>q.source.campus===2).length,25);assert.equal(qs.filter(q=>q.section==='research').length,25);assert.equal(new Set(qs.map(q=>q.hash)).size,50);});
test('missing campus fails',()=>assert.throws(()=>choose(pools.slice(0,1)),/Insufficient/));
test('single campus has all 50 questions',()=>assert.equal(choose(pools.slice(0,1),true).length,50));
test('duplicate pool cannot meet quota',()=>assert.throws(()=>choose([{...pools[0],questions:Array(50).fill(pools[0].questions[0])},pools[1]]),/Insufficient/));
test('generated Word has 50 numbered questions, no source answer key',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'qp-test-'));try{const ps=pools.map(p=>{const file=path.join(dir,p.campus+'.docx');fs.writeFileSync(file,fixture('Campus'+p.campus));return {...p,path:file};});const result=generate(choose(ps),'Mechanical Engineering','A'),z=new Zip(result),xml=z.file('word/document.xml').asText();assert.equal((xml.match(/Question \d+/g)||[]).length,50);assert.ok(!xml.includes('Answer Key'));assert.ok(xml.includes('January 2027'));assert.ok(z.file('[Content_Types].xml'));}finally{fs.rmSync(dir,{recursive:true,force:true});}});

function marksSummary(){const row=values=>'<w:tr>'+values.map(t=>`<w:tc><w:p><w:r><w:t>${t}</w:t></w:r></w:p></w:tc>`).join('')+'</w:tr>';return '<w:tbl>'+row(['Section','Topic','Number of Questions','Marks per Question','Total Marks'])+row(['A','Research Methodology','25','1','25'])+row(['B','Subject-Specific Core Topics','25','1','25'])+row(['Total','—','50','—','50'])+'</w:tbl>';}
test('Section A/B headings classify automatic numbered questions and ignore marks summary',()=>{
 const z=new Zip();const p=t=>`<w:p><w:r><w:t>${t}</w:t></w:r></w:p>`;let body='';
 for(const heading of ['Section A: Research Methodology (25 Questions | 1 Marks Each)','Section B: Subject-Specific Core Topics (25 Questions | 1 Mark Each)']){
  body+=p(heading);for(let i=1;i<=25;i++)body+=`<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="9"/></w:numPr></w:pPr><w:r><w:t>Which result applies to experiment ${i}?</w:t><w:br/><w:t>A. first</w:t><w:br/><w:t>B. second</w:t><w:br/><w:t>C. third</w:t><w:br/><w:t>D. fourth</w:t></w:r></w:p>`;
 }
 z.file('word/document.xml',`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}${marksSummary()}</w:body></w:document>`);
 z.file('word/numbering.xml','<w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:abstractNum w:abstractNumId="0"><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/></w:lvl></w:abstractNum><w:num w:numId="9"><w:abstractNumId w:val="0"/></w:num></w:numbering>');
 const result=inspect(z.generate({type:'nodebuffer'}));assert.equal(result.valid,true);assert.deepEqual(result.counts,{research:25,subject:25});assert.equal(result.questions.length,50);assert.ok(result.questions.every(q=>q.text.startsWith('Which result')));assert.ok(!result.questions.at(-1).text.includes('Total Marks'));assert.ok(!result.questions.at(-1).text.includes('Core Topics'));
});
test('marks-summary section names neither hide unclassified questions nor add question counts',()=>{
 const z=new Zip(fixture('unclassified'));let xml=z.file('word/document.xml').asText().replace(/<w:p><w:r><w:t>(Research Methodology|Subject-Specific Questions|Answer Key|1 A)<\/w:t><\/w:r><\/w:p>/g,'');
 xml=xml.replace('</w:body>',marksSummary()+'</w:body>');z.file('word/document.xml',xml);const result=inspect(z.generate({type:'nodebuffer'}));assert.equal(result.questions.length,50);assert.deepEqual(result.counts,{research:0,subject:0,unclassified:50});
});
